swagger: "2.0"
info:
  title: Funding Api
  description: Funding
  version: 1.0.0
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /product/all:
    get:
      tags:
      - product
      description: 获取全部产品信息
      operationId: ProductController.Get All Products
      responses:
        "200":
          description: ""
        "400":
          description: ""
  /product/detail/{id}:
    get:
      tags:
      - product
      description: 根据 id 获取带有套餐信息的指定产品信息
      operationId: ProductController.Get Product With Detail
      parameters:
      - in: path
        name: id
        description: 商品ID
        required: true
        type: string
      responses:
        "200":
          description: ""
        "400":
          description: ""
  /user/id/{id}:
    get:
      tags:
      - user
      description: 根据 Id（数据库表 Id ，不是用户名）来获取对应用户信息
      operationId: UserControllers.根据 id 获取 User
      parameters:
      - in: path
        name: id
        description: 数据库 User 表ID
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: ""
        "400":
          description: ""
definitions:
  models.Object:
    title: Object
    type: object
    properties:
      ObjectId:
        type: string
      PlayerName:
        type: string
      Score:
        type: integer
        format: int64
tags:
- name: user
  description: |
    用户相关
- name: product
  description: |
    产品相关
